DROP DATABASE CENTRODESALUDSRL
CREATE DATABASE CENTRODESALUDSRL
USE CENTRODESALUDSRL

CREATE TABLE NOMMEDICAMENTO
(
CLVNOMMEDICAMENTO INT IDENTITY(1,1) PRIMARY KEY,
NOMMEDICAMENTO VARCHAR(25) UNIQUE NOT NULL
)
CREATE TABLE TIPOMED
(
CLVTIPO INT IDENTITY(101, 1) PRIMARY KEY,
TIPO VARCHAR(20) UNIQUE NOT NULL
)
CREATE TABLE MEDICAMENTO
(
CLVMEDICAMENTO INT IDENTITY(31,1) PRIMARY KEY,
CLVNOMMEDICAMENTO INT FOREIGN KEY REFERENCES NOMMEDICAMENTO NOT NULL,
CLVTIPO INT FOREIGN KEY REFERENCES TIPOMED NOT NULL,
EXISTENCIAS INT DEFAULT(0) NOT NULL,
CONTENIDO VARCHAR(20),
FECHACADUCIDAD DATE
)
CREATE TABLE PACIENTE
(
CLVPACIENTE INT IDENTITY(121, 1) PRIMARY KEY,
NOMPACIENTE VARCHAR(50) NOT NULL,
PROCEDENCIA VARCHAR(30)
)
CREATE TABLE DESCRIPPACIENTE
(
CLVDESCRIPACIENTE INT IDENTITY(1,1) PRIMARY KEY,
CLVPACIENTE INT FOREIGN KEY REFERENCES PACIENTE NOT NULL,
DESCPACIENTE VARCHAR(100) NOT NULL
)
CREATE TABLE TURNODOC
(
CLVTURNO INT IDENTITY(211,1) PRIMARY KEY,
TURNO VARCHAR(25) UNIQUE NOT NULL
)
CREATE TABLE ESPECIALIDAD
(
CLVESPECIALIDAD INT IDENTITY(221, 1) PRIMARY KEY,
NOMESPECIALIDAD VARCHAR(25) UNIQUE NOT NULL
)
CREATE TABLE DOCTOR
(
CLVDOCTOR INT IDENTITY(245, 1) PRIMARY KEY,
NOMDOCTOR VARCHAR(50) NOT NULL,
CLVTURNO INT FOREIGN KEY REFERENCES TURNODOC NOT NULL,
CLVESPECIALIDAD INT FOREIGN KEY REFERENCES ESPECIALIDAD NOT NULL 
)
CREATE TABLE PACIENTEDOCTOR
(
CLVPACIENTEDOCTOR INT IDENTITY(1,1) PRIMARY KEY,
CLVPACIENTE INT FOREIGN KEY REFERENCES PACIENTE NOT NULL,
CLVDOCTOR INT FOREIGN KEY REFERENCES DOCTOR NOT NULL
)
CREATE TABLE RECETA
(
CLVRECETA INT IDENTITY(351, 1) PRIMARY KEY,
FECHAELAB DATE DEFAULT(GETDATE()) NOT NULL,
CLVDOCTOR INT FOREIGN KEY REFERENCES DOCTOR NOT NULL,
CLVPACIENTE INT FOREIGN KEY REFERENCES PACIENTE NOT NULL 
)
CREATE TABLE MEDICRECETAS
(
CLVMEDICRECETAS INT IDENTITY(1,1) PRIMARY KEY,
CLVMEDICAMENTO INT FOREIGN KEY REFERENCES MEDICAMENTO NOT NULL,
CLVRECETA INT FOREIGN KEY REFERENCES RECETA NOT NULL,
DESCRECETA VARCHAR(100)
)
DROP TABLE USUARIO
CREATE TABLE USUARIO
(
CLVDOCTOR INT PRIMARY KEY,
NOMUSUARIO VARCHAR(20) NOT NULL, 
CONTRASEÑA VARCHAR(20) NOT NULL
)