USE CENTRODESALUDSRL


--Insertar a NOMMEDICAMENTOS

SELECT * FROM NOMMEDICAMENTO

INSERT INTO NOMMEDICAMENTO
VALUES('PARACETAMOL')
INSERT INTO NOMMEDICAMENTO
VALUES('IBUPROFENO')
INSERT INTO NOMMEDICAMENTO
VALUES('SALBUTAMOL')
INSERT INTO NOMMEDICAMENTO
VALUES('OMEPRAZOL')
INSERT INTO NOMMEDICAMENTO
VALUES('AMOXICILINA')
INSERT INTO NOMMEDICAMENTO
VALUES('RAMIPIRIL')
INSERT INTO NOMMEDICAMENTO
VALUES('LANSOPRAZOL')
INSERT INTO NOMMEDICAMENTO
VALUES('SIMVASTATINA')
INSERT INTO NOMMEDICAMENTO
VALUES('AMPICILINA')
INSERT INTO NOMMEDICAMENTO
VALUES('CLOXACILINA')

--Insertar a TIPOMED

SELECT * FROM TIPOMED

INSERT INTO TIPOMED
VALUES('INHALACIÓN')
INSERT INTO TIPOMED
VALUES('INYECCIÓN')
INSERT INTO TIPOMED
VALUES('COMPRIMIDO')
INSERT INTO TIPOMED
VALUES('SUPOSITORIO')
INSERT INTO TIPOMED
VALUES('CAPSULA')
INSERT INTO TIPOMED
VALUES('LÍQUIDO ORAL')
INSERT INTO TIPOMED
VALUES('POLVO ORAL')
INSERT INTO TIPOMED
VALUES('POMADA')
INSERT INTO TIPOMED
VALUES('LOCIÓN')
INSERT INTO TIPOMED
VALUES('GOTAS OFTÁLMICAS')

--Insertar a MEDICAMENTO

SELECT * FROM MEDICAMENTO

INSERT INTO MEDICAMENTO
VALUES(1, 103, 30, '80 mg', '12/10/2020')		--Paracetamol comprimido
INSERT INTO MEDICAMENTO
VALUES(1, 104, 5, '125 mg', '11/13/2020')					--Supositorio
INSERT INTO MEDICAMENTO
VALUES(1, 106, 10, '15 mL', '10/13/2021')					--Líquido oral
INSERT INTO MEDICAMENTO
VALUES(2, 103, 2, '600 mg', '03/02/2021')		--Ibuprofeno comprimido
INSERT INTO MEDICAMENTO
VALUES(2, 106, 12, '40 mL', '05/06/2021')					--Líquido oral
INSERT INTO MEDICAMENTO
VALUES(3, 101, 5, '20 mg',  '06/15/2022')		--Sabutamol inhalación
INSERT INTO MEDICAMENTO
VALUES(3, 106, 15, '200 mL', '10/05/2022')					--Líquido oral
INSERT INTO MEDICAMENTO
VALUES(4, 105, 25, '20 mg', '01/04/2022')		--Omeprazol capsulas
INSERT INTO MEDICAMENTO
VALUES(5, 105, 30, '500 mg', '06/16/2022')		--Amoxicilina capsulas
INSERT INTO MEDICAMENTO
VALUES(5, 107, 5, '250 mg', '12/15/2022')					--Polvo oral
INSERT INTO MEDICAMENTO
VALUES(6, 103, 20, '10 mg', '05/15/2023')		--Ramipiril comprimido
INSERT INTO MEDICAMENTO
VALUES(6, 105, 21, '10 mg', '10/05/2023')					--Capsulas
INSERT INTO MEDICAMENTO
VALUES(7, 103, 20, '30 mg', '05/15/2023')		--Lanzoprazol comprimido
INSERT INTO MEDICAMENTO
VALUES(7, 105, 20, '30 mg', '06/15/2023')					--Capsulas
INSERT INTO MEDICAMENTO
VALUES(8, 103, 20, '40 mg', '04/05/2023')		--Simvastatina comprimido
INSERT INTO MEDICAMENTO
VALUES(9, 103, 20, '1 g', '05/15/2023')			--Ampicilina comprimido
INSERT INTO MEDICAMENTO
VALUES(9, 105, 40, '500 mg', '08/04/2023')					--Capsulas
INSERT INTO MEDICAMENTO
VALUES(9, 106, 15, '5 mL', '07/14/2023')					--Liquido oral
INSERT INTO MEDICAMENTO
VALUES(9, 102, 20, '1 g', '08/20/2023')						--Inyección
INSERT INTO MEDICAMENTO
VALUES(10, 105, 20, '500 mg', '07/12/2023')		--Cloxacilina capsulas
INSERT INTO MEDICAMENTO
VALUES(10, 102, 38, '500 mg', '09/04/2022')					--Inyección

--Insertar a PACIENTE

SELECT * FROM PACIENTE

INSERT INTO PACIENTE
VALUES('LUISA DIAZ AVALOS', 'SAHUAYO')
INSERT INTO PACIENTE
VALUES('CÉSAR CHAVEZ NAVA', 'JIQUILPAN')
INSERT INTO PACIENTE
VALUES('JAVIER MANZO HERNÁNDEZ', 'JACONA')
INSERT INTO PACIENTE
VALUES('JOSÉ ALEJO RIVAS', 'PALO ALTO')
INSERT INTO PACIENTE
VALUES('ÁNGEL ARIAS OLIVEROS', 'COJUMATLÁN')
INSERT INTO PACIENTE
VALUES('CARLOS JUAREZ CAMPOS', 'JIQUILPAN')
INSERT INTO PACIENTE
VALUES('CARLOS MERIDA ORDAZ', 'JIQUILPAN')

INSERT INTO PACIENTE
VALUES('CARLOS', 'JIQUILPAN')
select * from PACIENTE
INSERT INTO DESCRIPPACIENTE
VALUES(132, 'GASTRITIS')

select * from paciente
SELECT * FROM DESCRIPPACIENTE
DELETE DESCRIPPACIENTE WHERE CLVDESCRIPACIENTE=2

select PACIENTE.CLVPACIENTE, CLVDESCRIPACIENTE from PACIENTE, DESCRIPPACIENTE WHERE PACIENTE.CLVPACIENTE = DESCRIPPACIENTE.CLVPACIENTE

--Insertar a DESCRIPPACIENTE

SELECT * FROM DESCRIPPACIENTE

INSERT INTO DESCRIPPACIENTE
VALUES(121, 'DOLOR DE GARGANTA')		--Luisa Díaz
INSERT INTO DESCRIPPACIENTE
VALUES(121, 'FIEBRE')
INSERT INTO DESCRIPPACIENTE
VALUES(122, 'INFECCIÓN EN EL OÍDO')		--César Chávez
INSERT INTO DESCRIPPACIENTE
VALUES(123, 'GASTRITIS')				--Javier Manzo
INSERT INTO DESCRIPPACIENTE
VALUES(124, 'TOS FERINA')				--José Alejo
INSERT INTO DESCRIPPACIENTE
VALUES(125, 'ASMA')						--Ángel Arias
INSERT INTO DESCRIPPACIENTE
VALUES(126, 'INFECCIÓN DE GARGANTA')	--Carlos Juarez
INSERT INTO DESCRIPPACIENTE
VALUES(127, 'GASTRITIS')				--Carlos Merida


--Insertar a TURNODOC

SELECT * FROM TURNODOC

INSERT INTO TURNODOC
VALUES('MATUTINO')
INSERT INTO TURNODOC
VALUES('VESPERTINO')
INSERT INTO TURNODOC
VALUES('NOCTURNO')

--Insertar a ESPECIALIDAD

SELECT * FROM ESPECIALIDAD

INSERT INTO ESPECIALIDAD
VALUES('GASTROENTEROLOGÍA')
INSERT INTO ESPECIALIDAD
VALUES('GINECOLOGÍA')
INSERT INTO ESPECIALIDAD
VALUES('INFECTOLOGÍA')
INSERT INTO ESPECIALIDAD
VALUES('NEUROLOGÍA')
INSERT INTO ESPECIALIDAD
VALUES('NEUMOLOGÍA')
INSERT INTO ESPECIALIDAD
VALUES('OFTAMOLOGÍA')
INSERT INTO ESPECIALIDAD
VALUES('UROLOGÍA')
INSERT INTO ESPECIALIDAD
VALUES('RADIOLOGÍA')
INSERT INTO ESPECIALIDAD
VALUES('PEDIATRA')
INSERT INTO ESPECIALIDAD
VALUES('OTORRINOLARINGOLOGÍA')

--Insertar a DOCTOR

SELECT * FROM DOCTOR

INSERT INTO DOCTOR
VALUES('RICARDO PESCADOR SÁNCHEZ', 211, 229) --Matutino, Pediatra
INSERT INTO DOCTOR
VALUES('CRISTINA FLORES PAYAN', 212, 223)	--Vespertino, Infectología
INSERT INTO DOCTOR
VALUES('SERGIO CASTILLO SEGURA', 213, 230) --Nocturno, Otorrinolaringología
INSERT INTO DOCTOR
VALUES('HUGO ROSAS GARCÍA', 211, 225)		--Matutino, Neumológía
INSERT INTO DOCTOR
VALUES('HUMBERTO PEREZ PARTIDA', 211, 221)		--Matutino, Gastroenterología
--ADMIN
INSERT INTO DOCTOR
VALUES('SALVADOR RIVAS LEPEZ', 211, 221)

--Insertar a PACIENTEDOCTOR

SELECT * FROM PACIENTEDOCTOR

INSERT INTO PACIENTEDOCTOR
VALUES(121, 247)			--Luisa Díaz, Sergio Castillo
INSERT INTO PACIENTEDOCTOR
VALUES(122, 246)			--César Chávez, Cristina Flores
INSERT INTO PACIENTEDOCTOR
VALUES(123, 247)			--Javier Manzo, Sergio Castillo
INSERT INTO PACIENTEDOCTOR
VALUES(124, 245)			--José Alejo, Ricardo Pescador
INSERT INTO PACIENTEDOCTOR
VALUES(125, 248)			--Ángel Arias, Hugo Rosas
INSERT INTO PACIENTEDOCTOR
VALUES(126, 246)			--Carlos Juarez, Cristina Flores
INSERT INTO PACIENTEDOCTOR
VALUES(127, 249)			--Carlos Merida, Humberto Perez

--Insertar a RECETA

SELECT * FROM RECETA
/*SE OMITE LA FECHA DE ELABORACIÓN PORQUE ESTÁ POR DEFAULT A LA FECHA ACTUAL DE CUANDO SE HACE EL REGISTRO*/
INSERT INTO RECETA(CLVDOCTOR, CLVPACIENTE)
VALUES(247, 121)									--Sergio Castillo, Luisa Díaz. Fecha: 21/10/2020
INSERT INTO RECETA(CLVDOCTOR, CLVPACIENTE)
VALUES(246, 122)									--Cristina Flores, César Chávez. Fecha: 21/10/2020
INSERT INTO RECETA(CLVDOCTOR, CLVPACIENTE)
VALUES(247, 123)									--Sergio Castillo, Javier Manzo. Fecha: 21/10/2020
INSERT INTO RECETA(CLVDOCTOR, CLVPACIENTE)
VALUES(245, 124)									--Ricardo Pescador, José Alejo. Fecha: 21/10/2020
INSERT INTO RECETA(CLVDOCTOR, CLVPACIENTE)
VALUES(248, 125)									--Hugo Rosas, Ángel Arias. Fecha: 21/10/2020
INSERT INTO RECETA(CLVDOCTOR, CLVPACIENTE)
VALUES(246, 126)									--Cristina Flores, Carlos Juarez. Fecha: 08/11/2020
INSERT INTO RECETA(CLVDOCTOR, CLVPACIENTE)
VALUES(249, 127)									--Humberto Perez, Carlos Merida. Fecha: 15/11/2020
	
--Insertar a MEDICRECETAS

SELECT * FROM MEDICRECETAS

INSERT INTO MEDICRECETAS(CLVRECETA, CLVMEDICAMENTO, DESCRECETA)
VALUES(351, 31, 'TOMAR UNA TABLETA COMPRIMIDA CADA 8 HORAS')		--Paracetamol comprimido
INSERT INTO MEDICRECETAS(CLVRECETA, CLVMEDICAMENTO, DESCRECETA)
VALUES(351, 34, 'TOMAR UNA TABLETA COMPRIMIDA CADA 12 HORAS')	--Ibuprofeno comprimido
INSERT INTO MEDICRECETAS(CLVRECETA, CLVMEDICAMENTO, DESCRECETA)
VALUES(352, 39, 'TOMAR UNA CAPSULA CADA 8 HORAS')				--Amoxicilina capsulas
INSERT INTO MEDICRECETAS(CLVRECETA, CLVMEDICAMENTO, DESCRECETA)
VALUES(353, 38, 'TOMAR UNA CAPSULA CADA 8 HORAS')				--Omeprazol capsulas
INSERT INTO MEDICRECETAS(CLVRECETA, CLVMEDICAMENTO, DESCRECETA)
VALUES(354, 48, 'TOMAR UNA CUCHARADA CADA 8 HORAS')					--Ampicilina líquido oral
INSERT INTO MEDICRECETAS(CLVRECETA, CLVMEDICAMENTO, DESCRECETA)
VALUES(355, 36, 'INHALAR 3 VECES CADA 6 HORAS Y CADA QUE SE REQUIERA')	--Salbutamol inhalación
INSERT INTO MEDICRECETAS(CLVRECETA, CLVMEDICAMENTO, DESCRECETA)		--Amoxicilina polvo oral
VALUES(356, 40, 'TOMAR 20 MG CADA 12 HORAS')
INSERT INTO MEDICRECETAS(CLVRECETA, CLVMEDICAMENTO, DESCRECETA)		--Lanzoprazol capusas
VALUES(357, 44, 'TOMAR UNA CAPSULA CADA 8 HORAS')



--Insertar a USUARIOS

SELECT* FROM USUARIO

SELECT * FROM DOCTOR

INSERT INTO USUARIO VALUES(245, 'RICKYFISH', '12345')
INSERT INTO USUARIO VALUES(246, 'CRISTI', '12345')
INSERT INTO USUARIO VALUES(250, 'CHAVA13', '13')
INSERT INTO USUARIO VALUES(254, '254', '254')


