

/*INSERTA LOS NOMBRES DE LOS MEDICAMENTOS*/

/*CORRECTO*/
INSERTARNOMMEDICAMENTO 'AMLODIPINA'
/*NO PUEDE QUEDAR VACÍO*/
INSERTARNOMMEDICAMENTO ''
/*NOMBRES ÚNICOS*/
INSERTARNOMMEDICAMENTO 'AMLODIPINA'

SELECT * FROM NOMMEDICAMENTO

CREATE PROC INSERTARNOMMEDICAMENTO
@NOMMEDICAMENTO VARCHAR(25)

AS

DECLARE @CLVNOMMEDICAMENTO INT

IF (SELECT COUNT(*) FROM NOMMEDICAMENTO)=0
	SET  @CLVNOMMEDICAMENTO=1
ELSE
	SET  @CLVNOMMEDICAMENTO=(SELECT MAX(CLVNOMMEDICAMENTO) FROM NOMMEDICAMENTO)+1

IF @NOMMEDICAMENTO=''
	PRINT'EL NOMBRE DEL MEDICAMENTO NO PUEDE QUEDAR VACÍO.'
ELSE
	IF (SELECT COUNT(*) FROM NOMMEDICAMENTO WHERE NOMMEDICAMENTO=@NOMMEDICAMENTO)=0
		BEGIN
			BEGIN TRAN
				INSERT INTO NOMMEDICAMENTO
				VALUES(@CLVNOMMEDICAMENTO,@NOMMEDICAMENTO)
			COMMIT TRAN
		END
	ELSE
		PRINT'EL NOMBRE DEL MEDICAMENTO YA EXISTE.'




/*INSERTA LOS TIPOS DE MEDICAMENTOS*/

/*CORRECTO*/
INSERTARTIPOMED 'PÍLDORA'
/*NO PUEDE QUEDAR VACÍO*/
INSERTARTIPOMED ''
/*NOMBRES ÚNICOS*/
INSERTARTIPOMED 'PÍLDORA'

SELECT * FROM TIPOMED

CREATE PROC INSERTARTIPOMED
@TIPO VARCHAR(20)

AS

DECLARE @CLVTIPO INT

IF (SELECT COUNT(*) FROM TIPOMED)=0
	SET  @CLVTIPO=101
ELSE
	SET  @CLVTIPO=(SELECT MAX(CLVTIPO) FROM TIPOMED)+1

IF @TIPO=''
	PRINT'EL NOMBRE DEL TIPO DE MEDICAMENTO NO PUEDE QUEDAR VACÍO.'
ELSE
	IF (SELECT COUNT(*) FROM TIPOMED WHERE TIPO=@TIPO)=0
		BEGIN
			BEGIN TRAN
				INSERT INTO TIPOMED
				VALUES(@CLVTIPO,@TIPO)
			COMMIT TRAN
		
		END
	ELSE
		PRINT'EL NOMBRE DEL TIPO DE MEDICAMENTO YA EXISTE.'



/*INSERTA LOS ATRIBUTOS DE CADA MEDICAMENTO*/
/*LAS EXISTENCIAS SE PONEN POR DEFAULT EN 0, AÚN ASÍ LO DEJÉ EN EL PROCEDIMIENTO POR SI SE QUIERE ASIGNAR DE UNA VEZ LA CANTIDAD*/
/*CONTENIDO Y FECHA DE CADUCIDAD SE PUEDEN DEJAR VACÍOS, PERO IGUALMENTE LOS DEJÉ EN EL CASO DE QUE SE QUIERAN ESPECIFICAR
LOS CAMPOS DE UNA VEZ. EN ESTE CASO SÓLO DEJÉ LA FECHA COMO EJEMPLO.*/

/*CORRECTO*/
INSERTARMEDICAMENTO 11,111,'','','06/16/2022'
/*NOMBRE MEDICAMENTO NO ENCONTRADO*/
INSERTARMEDICAMENTO 12,111,'','','06/16/2022'
/*TIPO DE MEDICAMENTO NO ENCONTRADO*/
INSERTARMEDICAMENTO 11,112,'','','06/16/2022'
/*YA HAY UN REGISTRO CON EL MISMO MEDICAMENTO Y TIPO*/
INSERTARMEDICAMENTO 11,111,'','','06/16/2022'

SELECT * FROM MEDICAMENTO

CREATE PROC INSERTARMEDICAMENTO

@CLVNOMMEDICAMENTO INT,
@CLVTIPO INT,
@EXISTENCIAS INT,
@CONTENIDO VARCHAR(20),
@FECHACADUCIDAD DATE

AS

DECLARE @CLVMEDICAMENTO INT

IF (SELECT COUNT(*) FROM MEDICAMENTO)=0
	SET  @CLVMEDICAMENTO=31
ELSE
	SET  @CLVMEDICAMENTO=(SELECT MAX(CLVMEDICAMENTO) FROM MEDICAMENTO)+1

IF (SELECT COUNT(*) FROM NOMMEDICAMENTO WHERE CLVNOMMEDICAMENTO=@CLVNOMMEDICAMENTO)=1
	IF(SELECT COUNT(*) FROM TIPOMED WHERE CLVTIPO=@CLVTIPO)=1
		IF (SELECT COUNT(*) FROM MEDICAMENTO WHERE CLVNOMMEDICAMENTO=@CLVNOMMEDICAMENTO AND CLVTIPO=@CLVTIPO)=0
			BEGIN
				BEGIN TRAN
					INSERT INTO MEDICAMENTO
					VALUES(@CLVMEDICAMENTO, @CLVNOMMEDICAMENTO, @CLVTIPO, @EXISTENCIAS, @CONTENIDO, @FECHACADUCIDAD)
				COMMIT TRAN
			END
		ELSE
			PRINT 'YA HAY UN MEDICAMENTO CON LAS MISMAS CARACTERÍSTICAS.'
	ELSE
		PRINT 'NO SE ENCONTRÓ EL TIPO DE MEDICAMENTO.'
ELSE
	PRINT 'NO SE ENCONTRÓ EL NOMBRE DEL MEDICAMENTO.'




/*INSERTAR LAS EXISTENCIAS DEL MEDICAMENTO*/
/*SI EN EL CASO ANTERIOR NO SE ESPECIFICÓ LAS EXISTENCIAS, EN ESTE PROCEDIMIENTO SE PUEDE ACTUALIZAR*/

/*CORRECTO*/
ACTUALIZAREXISTENCIASMEDICAMENTO 52,30
/*NO ENCUENTRA EL MEDICAMENTO*/
ACTUALIZAREXISTENCIASMEDICAMENTO 53,30

SELECT * FROM MEDICAMENTO

CREATE PROC ACTUALIZAREXISTENCIASMEDICAMENTO
@CLVMEDICAMENTO INT,
@EXISTENCIAS INT

AS

IF (SELECT COUNT(*) FROM MEDICAMENTO WHERE CLVMEDICAMENTO=@CLVMEDICAMENTO)=1
	BEGIN
		BEGIN TRAN
			UPDATE MEDICAMENTO SET EXISTENCIAS = @EXISTENCIAS
			WHERE CLVMEDICAMENTO = @CLVMEDICAMENTO
		COMMIT TRAN
	END
ELSE
	PRINT'NO SE ENCONTRÓ EL MEDICAMENTO'


/*INSERTAR EL CONTENIDO DEL MEDICAMENTO*/
/*SI EN EL CASO ANTERIOR NO SE ESPECIFICÓ EL CONTENIDO, EN ESTE PROCEDIMIENTO SE PUEDE ACTUALIZAR*/

/*CORRECTO*/
ACTUALIZARCONTENIDOMEDICAMENTO 52,'500 mg'
/*NO ENCUENTRA EL MEDICAMENTO*/
ACTUALIZARCONTENIDOMEDICAMENTO 53,'500 mg'

SELECT * FROM MEDICAMENTO

CREATE PROC ACTUALIZARCONTENIDOMEDICAMENTO
@CLVMEDICAMENTO INT,
@CONTENIDO VARCHAR(20)

AS

IF (SELECT COUNT(*) FROM MEDICAMENTO WHERE CLVMEDICAMENTO=@CLVMEDICAMENTO)=1
	BEGIN
		BEGIN TRAN
			UPDATE MEDICAMENTO SET CONTENIDO = @CONTENIDO
			WHERE CLVMEDICAMENTO = @CLVMEDICAMENTO
		COMMIT TRAN
	END
ELSE
	PRINT'NO SE ENCONTRÓ EL MEDICAMENTO'




/*INSERTAR LA FECHA DE CADUCIDAD DEL MEDICAMENTO*/
/*SI EN EL CASO ANTERIOR NO SE ESPECIFICÓ LA FECHA DE CADUCIDAD, 
EN ESTE PROCEDIMIENTO SE PUEDE ACTUALIZAR*/

/*CORRECTO*/
ACTUALIZARFECHACADMEDICAMENTO 52,'12/15/2022'
/*NO ENCUENTRA EL MEDICAMENTO*/
ACTUALIZARFECHACADMEDICAMENTO 53,'12/15/2022'

SELECT * FROM MEDICAMENTO

CREATE PROC ACTUALIZARFECHACADMEDICAMENTO
@CLVMEDICAMENTO INT,
@FECHACADUCIDAD DATE

AS

IF (SELECT COUNT(*) FROM MEDICAMENTO WHERE CLVMEDICAMENTO=@CLVMEDICAMENTO)=1
	BEGIN
		BEGIN TRAN
			UPDATE MEDICAMENTO SET FECHACADUCIDAD = @FECHACADUCIDAD
			WHERE CLVMEDICAMENTO = @CLVMEDICAMENTO
		COMMIT TRAN
	END
ELSE
	PRINT'NO SE ENCONTRÓ EL MEDICAMENTO'


/*INSERTA LOS PACIENTES*/
/*PROCEDENCIA SE PUEDE DEJAR VACÍO, LO DEJÉ EN EL CASO DE QUE SE QUIERA ESPECIFICAR
EL CAMPO DE UNA VEZ. EN ESTE CASO NO LO ESPECIFÍCO, POR LO QUE SE QUEDA VACÍO.*/

/*CORRECTO*/
INSERTARPACIENTE 'TERESA REYES ORTEGA',''
/*EL NOMBRE DEL PACIENTE NO PUEDE QUEDAR VACÍO.*/
INSERTARPACIENTE '',''

SELECT * FROM PACIENTE

CREATE ALTER PROC INSERTARPACIENTE
@NOMPACIENTE VARCHAR(50),
@PROCEDENCIA VARCHAR(30),
@BAN INT OUTPUT

AS

DECLARE @CLVPACIENTE INT

IF (SELECT COUNT(*) FROM PACIENTE)=0
	SET  @CLVPACIENTE=121
ELSE
	SET  @CLVPACIENTE=(SELECT MAX(CLVPACIENTE) FROM PACIENTE)+1

IF @NOMPACIENTE=''
	SET @BAN=1
	--PRINT'EL NOMBRE DEL PACIENTE NO PUEDE QUEDAR VACÍO.'
	
ELSE
	BEGIN
		BEGIN TRAN
			INSERT INTO PACIENTE
			VALUES(@CLVPACIENTE,@NOMPACIENTE,@PROCEDENCIA)
		COMMIT TRAN
	END
	


/*INSERTAR LA PROCEDENCIA DE LOS PACIENTES*/
/*SI EN EL CASO ANTERIOR NO SE ESPECIFICÓ LA PROCEDENCIA, 
EN ESTE PROCEDIMIENTO SE PUEDE ACTUALIZAR*/

/*CORRECTO*/
ACTUALIZARPROCEDENCIAPACIENTE 128,'PETATÁN'
/*NO ENCUENTRA EL PACIENTE*/
ACTUALIZARPROCEDENCIAPACIENTE 129,'PETATÁN'

SELECT * FROM PACIENTE

CREATE PROC ACTUALIZARPROCEDENCIAPACIENTE
@CLVPACIENTE INT,
@PROCEDENCIA VARCHAR(30)

AS

IF (SELECT COUNT(*) FROM PACIENTE WHERE CLVPACIENTE=@CLVPACIENTE)=1
	BEGIN
		BEGIN TRAN
			UPDATE PACIENTE SET PROCEDENCIA = @PROCEDENCIA
			WHERE CLVPACIENTE = @CLVPACIENTE
		COMMIT TRAN
	END
ELSE
	PRINT'NO SE ENCONTRÓ EL PACIENTE'



/*INSERTA LA DESCRIPCIÓN DEL PACIENTE*/

/*CORRECTO*/
INSERTARDESCRIPPACIENTE 128,'PRESIÓN ARTERIAL ALTA'
/*NO SE ENCUENTRA EL PACIENTE*/
INSERTARDESCRIPPACIENTE 129,'PRESIÓN ARTERIAL ALTA'
/*NO HAY DESCRIPCIÓN*/
INSERTARDESCRIPPACIENTE 128,''
/*REGISTRO REPETIDO*/
INSERTARDESCRIPPACIENTE 128,'PRESIÓN ARTERIAL ALTA'

SELECT * FROM DESCRIPPACIENTE

CREATE PROC INSERTARDESCRIPPACIENTE
@CLVPACIENTE INT,
@DESCPACIENTE VARCHAR(100)

AS

IF (SELECT COUNT(*) FROM PACIENTE WHERE CLVPACIENTE=@CLVPACIENTE)=1
	IF @DESCPACIENTE=''
		PRINT'COLOQUE UNA DESCRIPCIÓN'
	ELSE
		IF (SELECT COUNT(*) FROM DESCRIPPACIENTE WHERE DESCPACIENTE=@DESCPACIENTE AND CLVPACIENTE=@CLVPACIENTE)=1
			PRINT'EL REGISTRO YA EXISTE.'
		ELSE
			BEGIN
				BEGIN TRAN
					INSERT INTO DESCRIPPACIENTE
					VALUES(@CLVPACIENTE, @DESCPACIENTE)
				COMMIT TRAN
			END
ELSE
	PRINT'NO SE ENCONTRÓ EL PACIENTE'



/*INSERTAR EL TURNO DEL DOCTOR*/

/*CORRECTO*/
INSERTARTURNODOC 'MIXTO'
/*NO PUEDE QUEDAR VACÍO*/
INSERTARTURNODOC ''
/*EL TURNO YA EXISTE*/
INSERTARTURNODOC 'MIXTO'

SELECT * FROM TURNODOC

CREATE PROC INSERTARTURNODOC
@TURNO VARCHAR(25)

AS

DECLARE @CLVTURNO INT

IF (SELECT COUNT(*) FROM TURNODOC)=0
	SET  @CLVTURNO=211
ELSE
	SET  @CLVTURNO=(SELECT MAX(CLVTURNO) FROM TURNODOC)+1

IF @TURNO=''
	PRINT'EL NOMBRE DEL TURNO DEL DOCTOR NO PUEDE QUEDAR VACÍO.'
ELSE
	IF (SELECT COUNT(*) FROM TURNODOC WHERE TURNO=@TURNO)=0
		BEGIN
			BEGIN TRAN
				INSERT INTO TURNODOC
				VALUES(@CLVTURNO,@TURNO)
			COMMIT TRAN
		END
	ELSE
		PRINT'EL NOMBRE DEL TURNO DEL DOCTOR YA EXISTE.'




/*INSERTAR LA ESPECIALIDAD DEL DOCTOR*/

/*CORRECTO*/
INSERTARESPECIALIDAD 'CARDIOLOGÍA'
/*NO PUEDE QUEDAR VACÍO*/
INSERTARESPECIALIDAD ''
/*LA ESPECIALIDAD YA EXISTE*/
INSERTARESPECIALIDAD 'CARDIOLOGÍA'

SELECT * FROM ESPECIALIDAD

CREATE PROC INSERTARESPECIALIDAD
@NOMESPECIALIDAD VARCHAR(25)

AS

DECLARE @CLVESPECIALIDAD INT

IF (SELECT COUNT(*) FROM ESPECIALIDAD)=0
	SET  @CLVESPECIALIDAD=221
ELSE
	SET  @CLVESPECIALIDAD=(SELECT MAX(CLVESPECIALIDAD) FROM ESPECIALIDAD)+1

IF @NOMESPECIALIDAD=''
	PRINT'EL NOMBRE DE LA ESPECIALIDAD NO PUEDE QUEDAR VACÍO.'
ELSE
	IF (SELECT COUNT(*) FROM ESPECIALIDAD WHERE NOMESPECIALIDAD=@NOMESPECIALIDAD)=0
		BEGIN
			BEGIN TRAN
				INSERT INTO ESPECIALIDAD
				VALUES(@CLVESPECIALIDAD,@NOMESPECIALIDAD)
			COMMIT TRAN	
		END
	ELSE
		PRINT'EL NOMBRE DE LA ESPECIALIDAD YA EXISTE.'


/*INSERTA AL DOCTOR*/

/*CORRECTO*/
INSERTARDOCTOR 'CHRISTOFER NUÑEZ GARCÍA', 214, 231
/*NOMBRE VACÍO*/
INSERTARDOCTOR '', 214, 231
/*NO SE ENCONTRÓ EL TURNO*/
INSERTARDOCTOR 'CHRISTOFER NUÑEZ GARCÍA', 215, 231
/*NO SE ENCONTRÓ LA ESPECIALIDAD*/
INSERTARDOCTOR 'CHRISTOFER NUÑEZ GARCÍA', 214, 232
/*EL REGISTRO YA EXISTE*/
INSERTARDOCTOR 'CHRISTOFER NUÑEZ GARCÍA', 214, 231

SELECT * FROM DOCTOR

CREATE PROC INSERTARDOCTOR

@NOMDOCTOR VARCHAR(50),
@CLVTURNO INT,
@CLVESPECIALIDAD INT

AS

DECLARE @CLVDOCTOR INT

IF (SELECT COUNT(*) FROM DOCTOR)=0
	SET  @CLVDOCTOR=245
ELSE
	SET  @CLVDOCTOR=(SELECT MAX(CLVDOCTOR) FROM DOCTOR)+1

IF @NOMDOCTOR=' '
	PRINT 'EL NOMBRE DEL DOCTOR NO PUEDE QUEDAR VACÍO.'
ELSE
	IF (SELECT COUNT(*) FROM TURNODOC WHERE CLVTURNO=@CLVTURNO)=1 
		IF(SELECT COUNT(*) FROM ESPECIALIDAD WHERE CLVESPECIALIDAD=@CLVESPECIALIDAD)=1
			IF (SELECT COUNT(*) FROM DOCTOR WHERE CLVTURNO=@CLVTURNO AND CLVESPECIALIDAD=@CLVESPECIALIDAD AND NOMDOCTOR=@NOMDOCTOR)=0
				BEGIN
					BEGIN TRAN
						INSERT INTO DOCTOR
						VALUES(@CLVDOCTOR, @NOMDOCTOR, @CLVTURNO, @CLVESPECIALIDAD)
					COMMIT TRAN
				END
			ELSE
				PRINT 'EL REGISTRO YA EXISTE'
		ELSE
			PRINT 'NO SE ENCONTRÓ ESA ESPECIALIDAD'
	ELSE
		PRINT 'NO SE ENCONTRÓ ESE TURNO'




/*SE INSERTA LA RELACIÓN ENTRE PACIENTE Y DOCTOR*/

/*CORRECTO*/
INSERTARPACIENTEDOCTOR 128,250
/*NO SE ENCUENTRA EL PACIENTE*/
INSERTARPACIENTEDOCTOR 129,250
/*NO SE ENCUENTRA EL DOCTOR*/
INSERTARPACIENTEDOCTOR 128,251
/*EL REGISTRO DE LA RELACIÓN YA EXISTE*/
INSERTARPACIENTEDOCTOR 128,250

SELECT * FROM PACIENTEDOCTOR
		
CREATE PROC INSERTARPACIENTEDOCTOR
@CLVPACIENTE INT,
@CLVDOCTOR INT

AS

IF (SELECT COUNT(*) FROM PACIENTE WHERE CLVPACIENTE=@CLVPACIENTE)=1
	IF (SELECT COUNT(*) FROM DOCTOR WHERE CLVDOCTOR=@CLVDOCTOR)=1
		IF(SELECT COUNT(*) FROM PACIENTEDOCTOR WHERE CLVPACIENTE=@CLVPACIENTE AND CLVDOCTOR=@CLVDOCTOR)=0
			BEGIN
				BEGIN TRAN
					INSERT INTO PACIENTEDOCTOR
					VALUES(@CLVPACIENTE, @CLVDOCTOR)
				COMMIT TRAN
			END
		ELSE
			PRINT 'YA EXISTE ESE REGISTRO'
	ELSE
		PRINT 'NO SE ENCONTRÓ EL DOCTOR EN LA BASE DE DATOS.'
ELSE
	PRINT 'NO SE ENCONTRÓ EL PACIENTE EN LA BASE DE DATOS.'
	


/*INSERTA LA RECETA MÉDICA*/
/*LA FECHA DE ELABORACIÓN SE TOMA POR DEFAULT EL DÍA EN QUE SE CREA*/

/*CORRECTO*/
INSERTARRECETA 128,250
/*NO SE ENCUENTRA EL PACIENTE*/
INSERTARRECETA 129,250
/*NO SE ENCUENTRA EL DOCTOR*/
INSERTARRECETA 128,251
/*NO SE TOMÓ EN CUENTA QUE EL REGISTRO NO SE REPITA
DEBIDO A QUE EL MISMO DOCTOR PUEDE DAR OTRA CONSULTA A LA MISMA PERSONA
A LO LARGO DEL MISMO DÍA*/

SELECT * FROM RECETA

CREATE PROC INSERTARRECETA

@CLVPACIENTE INT,
@CLVDOCTOR INT


AS

DECLARE @CLVRECETA INT

IF (SELECT COUNT(*) FROM RECETA)=0
	SET  @CLVRECETA=351
ELSE
	SET  @CLVRECETA=(SELECT MAX(CLVRECETA) FROM RECETA)+1

IF (SELECT COUNT(*) FROM PACIENTE WHERE CLVPACIENTE=@CLVPACIENTE)=1
	IF (SELECT COUNT(*) FROM DOCTOR WHERE CLVDOCTOR=@CLVDOCTOR)=1
		BEGIN
			BEGIN TRAN
				INSERT INTO RECETA(CLVRECETA, CLVPACIENTE, CLVDOCTOR)
				VALUES(@CLVRECETA, @CLVPACIENTE, @CLVDOCTOR)
			COMMIT TRAN
		END
	ELSE
		PRINT 'NO SE ENCONTRÓ EL DOCTOR'
ELSE
	PRINT 'NO SE ENCONTRÓ EL PACIENTE'



/*INSERTA LA RELACIÓN ENTRE LOS MEDICAMENTOS Y LA RECETA MÉDICA*/

/*CORRECTO*/
INSERTARMEDICRECETAS 52,358,'TOMAR UNA PÍLDORA CADA 10 HORAS'
/*NO SE ENCONTRÓ EL MEDICAMENTO*/
INSERTARMEDICRECETAS 53,358,'TOMAR UNA PÍLDORA CADA 10 HORAS'
/*NO SE ENCONTRÓ LA RECETA MÉDICA*/
INSERTARMEDICRECETAS 52,359,'TOMAR UNA PÍLDORA CADA 10 HORAS'

SELECT * FROM MEDICRECETAS

CREATE PROC INSERTARMEDICRECETAS

@CLVMEDICAMENTO INT,
@CLVRECETA INT,
@DESCRECETA VARCHAR(100)

AS

IF (SELECT COUNT(*) FROM MEDICAMENTO WHERE CLVMEDICAMENTO=@CLVMEDICAMENTO)=1
	IF (SELECT COUNT(*) FROM RECETA WHERE CLVRECETA=@CLVRECETA)=1
		BEGIN
			BEGIN TRAN
				INSERT INTO MEDICRECETAS
				VALUES(@CLVMEDICAMENTO, @CLVRECETA, @DESCRECETA)
			COMMIT TRAN
		END
	ELSE
		PRINT 'NO SE ENCONTRÓ LA RECETA MÉDICA'
ELSE
	PRINT 'NO SE ENCONTRÓ EL MEDICAMENTO'




