CREATE PROC INSERTARPACIENTE
@NOMPACIENTE VARCHAR(50),
@PROCEDENCIA VARCHAR(30),
@BAN INT OUTPUT

AS

DECLARE @CLVPACIENTE INT

IF (SELECT COUNT(*) FROM PACIENTE)=0
	SET  @CLVPACIENTE=121
ELSE
	SET  @CLVPACIENTE=(SELECT MAX(CLVPACIENTE) FROM PACIENTE)+1

IF @NOMPACIENTE=''
	SET @BAN=1
	--PRINT'EL NOMBRE DEL PACIENTE NO PUEDE QUEDAR VACÍO.'
	
ELSE
	BEGIN
		BEGIN TRAN
			INSERT INTO PACIENTE
			VALUES(@CLVPACIENTE,@NOMPACIENTE,@PROCEDENCIA)
		COMMIT TRAN
	END
	